name: validate ilastik collection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BIOIMAGEIO_COUNT_RDF_DOWNLOADS: 'false'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: install bioimageio.spec
      run: pip install bioimageio.spec lxml
    - name: validate collection
      run: bioimageio validate-partner-collection collection.yaml
#    - name: trigger collection update
#      uses: octokit/request-action@v2.x
#      env:
#        GITHUB_TOKEN: ${{ secrets.PAT }}
#      with:
#        route: POST /repos/bioimage-io/collection-bioimage-io/actions/workflows/auto_update_main.yaml/dispatches
#        ref: refs/heads/main
